# Generated by Django 2.2.4 on 2019-08-08 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=50)),
                ('exercise_name_1', models.CharField(max_length=50)),
                ('sets_exercise_1', models.PositiveIntegerField(default='0')),
                ('reps_exercise_1', models.PositiveIntegerField(default='0')),
                ('exercise_name_2', models.CharField(max_length=50)),
                ('sets_exercise_2', models.PositiveIntegerField(default='0')),
                ('reps_exercise_2', models.PositiveIntegerField(default='0')),
                ('exercise_name_3', models.CharField(max_length=50)),
                ('sets_exercise_3', models.PositiveIntegerField(default='0')),
                ('reps_exercise_3', models.PositiveIntegerField(default='0')),
                ('exercise_name_4', models.CharField(max_length=50)),
                ('sets_exercise_4', models.PositiveIntegerField(default='0')),
                ('reps_exercise_4', models.PositiveIntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
